PreCommit:
  RuboCop:
    enabled: true
    required_executable: './bin/rubocop'
    command: ['bundle', 'exec', 'rubocop']
    install_command: 'bundle install'
    flags: ['--format=emacs', '--force-exclusion', '--display-cop-names', '--fail-level=C']
    problem_on_unmodified_line: ignore
    on_warn: fail
    quiet: false
    # levels:
    # refactor convention warning error fatal
    # R: :refactor, C: :convention, W: :warning, E: :error, F: :fatal
  ForbiddenBranches:
    enabled: true
    branch_patterns: ['master', 'nextrel']
    on_warn: fail
    quiet: false
PostCheckout:
  ShouldBundleInstall:
    enabled: true
    quiet: false
PostMerge:
  ShouldBundleInstall:
    enabled: true
    quiet: false