PreCommit:
  RuboCop:
    enabled: true
    required_executable: './bin/rubocop'
    command: ['bundle', 'exec', 'rubocop']
    install_command: 'bundle install'
    flags: ['--format=emacs', '--force-exclusion', '--display-cop-names', '--fail-level=C']
    problem_on_unmodified_line: ignore
    on_warn: fail
    quiet: false
    # levels:
    # refactor convention warning error fatal
    # R: :refactor, C: :convention, W: :warning, E: :error, F: :fatal
  ForbiddenBranches:
    enabled: true
    branch_patterns: ['master', 'nextrel']
    on_warn: fail
    quiet: false
PostMerge:
  BundleInstall:
    enabled: true
    quiet: false
    required_executable: 'bundle'

PrepareCommitMsg:
  ALL:
    requires_files: false
    required: false
    quiet: false
  ReplaceBranch:
    enabled: true
    description: 'Prepends the commit message with text based on the branch name'
    branch_pattern: '\A(.*\w+[-_]\d+).*\z'
    replacement_text: '\1'
    skipped_commit_types: ['message', 'template', 'merge', 'squash']
    on_fail: warn