# MySQL.  Versions 4.1 and 5.0 are recommended.
#
# Install the MYSQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
<% require 'states' %>

<%
def define_db(name, db, legacy, includes)
  <<-EOF
  #{name}:
    <<: *#{includes}
    database: #{db}
    legacy: #{legacy}
  #{name}_ro:
    <<: *#{includes}_ro
    database: #{db}
  EOF
end
%>

mysql: &mysql
  adapter: mysql2
  encoding: utf8
  pool: 7
  username: root

mysql_localhost: &mysql_localhost
  <<: *mysql
  host: localhost
  password:
mysql_localhost_rw: &mysql_localhost_rw
  <<: *mysql_localhost
mysql_localhost_ro: &mysql_localhost_ro
  <<: *mysql_localhost

mysql_dev: &mysql_dev
  <<: *mysql
  host: dev.greatschools.org
  username: service
  password: service
mysql_dev_rw: &mysql_dev_rw
  <<: *mysql_dev
mysql_dev_ro: &mysql_dev_ro
  <<: *mysql_dev

development: &development
  <<: *mysql_localhost
  database: LocalizedProfiles_development
  profile_config:
    <<: *mysql_localhost
    database: LocalizedProfiles_development
    legacy: false
  profile_config_ro:
    <<: *mysql_localhost_ro
    database: LocalizedProfiles_development
    legacy: false
  _STATE_:
    <<: *mysql_localhost
    database: __STATE_
    legacy: true
  _STATE__ro:
    <<: *mysql_localhost_ro
    database: __STATE_
    legacy: true
  gs_schooldb:
    <<: *mysql_localhost
    database: gs_schooldb
    legacy: true
  gs_schooldb_ro:
    <<: *mysql_localhost_ro
    database: gs_schooldb
    legacy: true
  surveys:
    <<: *mysql_localhost
    database: surveys
    legacy: true
  surveys_ro:
    <<: *mysql_localhost_ro
    database: surveys
    legacy: true
  community:
    <<: *mysql_localhost
    database: community
    legacy: true
  community_ro:
    <<: *mysql_localhost_ro
    database: community
    legacy: true
  us_geo:
    <<: *mysql_localhost
    database: us_geo
    legacy: true
  us_geo_ro:
    <<: *mysql_localhost_ro
    database: us_geo
    legacy: true

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.

test: &test
  <<: *mysql_localhost
  database: LocalizedProfiles_test
  profile_config:
    <<: *mysql_localhost
    database: LocalizedProfiles_test
    legacy: false
  profile_config_ro:
    <<: *mysql_localhost_ro
    database: LocalizedProfiles_test
    legacy: false
  _STATE_:
    <<: *mysql_localhost
    database: __STATE__test
    legacy: true
  _STATE__ro:
    <<: *mysql_localhost_ro
    database: __STATE__test
    legacy: true
  gs_schooldb:
    <<: *mysql_localhost
    database: gs_schooldb_test
    legacy: true
  gs_schooldb_ro:
    <<: *mysql_localhost_ro
    database: gs_schooldb_test
    legacy: true
  surveys:
    <<: *mysql_localhost
    database: surveys_test
    legacy: true
  surveys_ro:
    <<: *mysql_localhost_ro
    database: surveys_test
    legacy: true
  community:
    <<: *mysql_localhost
    database: community_test
    legacy: true
  community_ro:
    <<: *mysql_localhost_ro
    database: community_test
    legacy: true
  us_geo:
    <<: *mysql_localhost
    database: us_geo_test
    legacy: true
  us_geo_ro:
    <<: *mysql_localhost_ro
    database: us_geo_test
    legacy: true

cucumber:
  <<: *test

profile:
  <<: *development
