# MySQL.  Versions 4.1 and 5.0 are recommended.
#
# Install the MYSQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html

mysql: &mysql
  adapter: mysql2
  encoding: utf8
  pool: 7
  username: root

mysql_localhost: &mysql_localhost
  <<: *mysql
  host: localhost
  password:

mysql_localhost_rw: &mysql_localhost_rw
  <<: *mysql_localhost

mysql_localhost_ro: &mysql_localhost_ro
  <<: *mysql_localhost

mysql_dev: &mysql_dev
  <<: *mysql
  host: dev.greatschools.org
  username: service
  password: service

mysql_dev_rw: &mysql_dev_rw
  <<: *mysql_dev

mysql_dev_ro: &mysql_dev_ro
  <<: *mysql_dev

mysql_rw_server_to_use_in_development: &mysql_rw_server_to_use_in_development
  <<: *mysql_localhost_rw

mysql_ro_server_to_use_in_development: &mysql_ro_server_to_use_in_development
  <<: *mysql_localhost_ro

development: &development
  <<: *mysql_rw_server_to_use_in_development
  database: LocalizedProfiles_development
  profile_config_rw:
    <<: *mysql_rw_server_to_use_in_development
    database: LocalizedProfiles_development
    legacy: false
  profile_config:
    <<: *mysql_ro_server_to_use_in_development
    database: LocalizedProfiles_development
    legacy: false
  _STATE__rw:
    <<: *mysql_rw_server_to_use_in_development
    database: __STATE_
    legacy: true
  _STATE_:
    <<: *mysql_ro_server_to_use_in_development
    database: __STATE_
    legacy: true
  gs_schooldb_rw:
    <<: *mysql_rw_server_to_use_in_development
    database: gs_schooldb
    legacy: true
  gs_schooldb:
    <<: *mysql_ro_server_to_use_in_development
    database: gs_schooldb
    legacy: true
  surveys_rw:
    <<: *mysql_rw_server_to_use_in_development
    database: surveys
    legacy: true
  surveys:
    <<: *mysql_ro_server_to_use_in_development
    database: surveys
    legacy: true
  community_rw:
    <<: *mysql_rw_server_to_use_in_development
    database: community
    legacy: true
  community:
    <<: *mysql_ro_server_to_use_in_development
    database: community
    legacy: true
  us_geo_rw:
    <<: *mysql_rw_server_to_use_in_development
    database: us_geo
    legacy: true
  us_geo:
    <<: *mysql_ro_server_to_use_in_development
    database: us_geo
    legacy: true
  gscms_pub_rw:
    <<: *mysql_rw_server_to_use_in_development
    database: gscms_pub
    legacy: true
  gscms_pub:
    <<: *mysql_ro_server_to_use_in_development
    database: gscms_pub
    legacy: true

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.

test: &test
  <<: *mysql_localhost_rw
  database: localized_profiles_test
  profile_config_rw:
    <<: *mysql_localhost_rw
    database: localized_profiles_test
    legacy: false
  profile_config:
    <<: *mysql_localhost_rw
    database: localized_profiles_test
    legacy: false
  _STATE__rw:
    <<: *mysql_localhost_rw
    database: __STATE__test
    legacy: true
  _STATE_:
    <<: *mysql_localhost_rw
    database: __STATE__test
    legacy: true
  gs_schooldb_rw:
    <<: *mysql_localhost_rw
    database: gs_schooldb_test
    legacy: true
  gs_schooldb:
    <<: *mysql_localhost_rw
    database: gs_schooldb_test
    legacy: true
  surveys_rw:
    <<: *mysql_localhost_rw
    database: surveys_test
    legacy: true
  surveys:
    <<: *mysql_localhost_rw
    database: surveys_test
    legacy: true
  community_rw:
    <<: *mysql_localhost_rw
    database: community_test
    legacy: true
  community:
    <<: *mysql_localhost_rw
    database: community_test
    legacy: true
  us_geo_rw:
    <<: *mysql_localhost_rw
    database: us_geo_test
    legacy: true
  us_geo:
    <<: *mysql_localhost_rw
    database: us_geo_test
    legacy: true
  gscms_pub_rw:
    <<: *mysql_localhost_rw
    database: gscms_pub_test
    legacy: true
  gscms_pub:
    <<: *mysql_localhost_rw
    database: gscms_pub_test
    legacy: true

cucumber:
  <<: *test

profile:
  <<: *development
