# MySQL.  Versions 4.1 and 5.0 are recommended.
# 
# Install the MYSQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
<% require 'states' %>

<%
def define_db(name, db, legacy, includes)
  <<-EOF
  #{name}:
    <<: *#{includes}
    database: #{db}
    legacy: #{legacy}
  #{name}_ro:
    <<: *#{includes}_ro
    database: #{db}
  EOF
end
%>


mysql: &mysql
  adapter: mysql2
  encoding: utf8
  pool: 7
  username: root

mysql_localhost: &mysql_localhost
  <<: *mysql
  host: 127.0.0.1
  password:
mysql_localhost_rw: &mysql_localhost_rw
  <<: *mysql_localhost
mysql_localhost_ro: &mysql_localhost_ro
  <<: *mysql_localhost

mysql_dev: &mysql_dev
  <<: *mysql
  host: dev.greatschools.org
  username: service
  password: service
mysql_dev_rw: &mysql_dev_rw
  <<: *mysql_dev
mysql_dev_ro: &mysql_dev_ro
  <<: *mysql_dev


development:
  <<: *mysql_localhost
  database: LocalizedProfiles_development
<%= define_db('profile_config', 'LocalizedProfiles_development', false, 'mysql_localhost') %>
<% States.state_hash.values.each do |abbreviation| %>
<%= define_db(abbreviation.downcase, '_' + abbreviation.downcase, true, 'mysql_localhost') %>
<% end %>
<%= define_db('gs_schooldb', 'gs_schooldb', true, 'mysql_localhost') %>
<%= define_db('surveys', 'surveys', true, 'mysql_localhost') %>
<%= define_db('community', 'community', true, 'mysql_localhost') %>


# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.

#Just using _ca_test and _dc_test for testing. We can add other states for testing if needed.
test: &test
  <<: *mysql_localhost
  database: LocalizedProfiles_test
  profile_config:
    <<: *mysql_localhost
    database: LocalizedProfiles_test
  ca:
    <<: *mysql_localhost
    database: _ca_test
    legacy: true
  dc:
     <<: *mysql_localhost
     database: _dc_test
     legacy: true
  gs_schooldb:
    <<: *mysql_localhost
    database: gs_schooldb_test
    legacy: true
  surveys:
    <<: *mysql_localhost
    database: surveys_test
    legacy: true
  community:
      <<: *mysql_localhost
      database: community_test
      legacy: true

cucumber:
  <<: *test

<%= file = File.join('', 'usr', 'local', 'etc', 'GSWebRuby-database.yml') ; File.read(file) if File.exist?(file) %>

