# MySQL.  Versions 4.1 and 5.0 are recommended.
# 
# Install the MYSQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
<% require 'States' %>

mysql: &mysql
  adapter: mysql2
  encoding: utf8
  pool: 7
  username: root

mysql_localhost: &mysql_localhost
  <<: *mysql
  host: 127.0.0.1
  password:

mysql_production: &mysql_production
  <<: *mysql

mysql_dev: &mysql_dev
  <<: *mysql
  host: dev.greatschools.org
  username: service
  password: service

development:
  <<: *mysql_localhost
  profile_config:
    <<: *mysql_localhost
    database: LocalizedProfiles_development
<% States.state_hash.values.each do |abbreviation| %>
  <%= abbreviation.downcase %>:
    <<: *mysql_localhost
    database: _<%= abbreviation.downcase %>
<% end %>
  gs_schooldb:
    <<: *mysql_localhost
    database: gs_schooldb
  surveys:
    <<: *mysql_localhost
    database: surveys

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test: &test
  <<: *mysql_localhost
  profile_config:
    <<: *mysql_localhost
    database: LocalizedProfiles_development
<% States.state_hash.values.each do |abbreviation| %>
  <%= abbreviation.downcase %>:
    <<: *mysql_localhost
    database: _<%= abbreviation.downcase %>
<% end %>
  gs_schooldb:
    <<: *mysql_localhost
    database: gs_schooldb
  surveys:
    <<: *mysql_localhost
    database: surveys

cucumber:
  <<: *test