# MySQL.  Versions 4.1 and 5.0 are recommended.
#
# Install the MYSQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html

mysql: &mysql
  adapter: mysql2
  encoding: utf8
  pool: 7
  username: root
  read_timeout: 20
  write_timeout: 20
  connect_timeout: 5

mysql_rw_server: &mysql_rw_server
  <<: *mysql
  host: localhost
  password:

mysql_ro_server: &mysql_ro_server
  <<: *mysql
  host: localhost
  password:

mysql_gsdata: &mysql_gsdata
  <<: *mysql
  host: localhost
  username: root
  password:

development: &development
  <<: *mysql_rw_server
  database: gs_schooldb
  profile_config_rw:
    <<: *mysql_rw_server
    database: localized_profiles
    legacy: false
  profile_config:
    <<: *mysql_ro_server
    database: localized_profiles
    legacy: false
  _STATE__rw:
    <<: *mysql_rw_server
    database: __STATE_
    legacy: true
  _STATE_:
    <<: *mysql_ro_server
    database: __STATE_
    legacy: true
  gs_schooldb_rw:
    <<: *mysql_rw_server
    database: gs_schooldb
    legacy: true
  gs_schooldb:
    <<: *mysql_ro_server
    database: gs_schooldb
    legacy: true
  community_rw:
    <<: *mysql_rw_server
    database: community
    legacy: true
  community:
    <<: *mysql_ro_server
    database: community
    legacy: true
  us_geo_rw:
    <<: *mysql_rw_server
    database: us_geo
    legacy: true
  us_geo:
    <<: *mysql_ro_server
    database: us_geo
    legacy: true
  gsdata:
    <<: *mysql_gsdata
    database: gsdata
    legacy: false
  omni:
    <<: *mysql_gsdata
    database: omni
    legacy: false
  api_rw:
    <<: *mysql_rw_server
    database: api
    legacy: true
  api:
    <<: *mysql_ro_server
    database: api
    legacy: true
# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test_db: &test_db
  <<: *mysql
  host: localhost
  password:

test: &test
  <<: *test_db
  database: gs_schooldb_test
  profile_config_rw:
    <<: *test_db
    database: localized_profiles_test
    legacy: true
  profile_config:
    <<: *test_db
    database: localized_profiles_test
    legacy: true
  _STATE__rw:
    <<: *test_db
    database: __STATE__test
    legacy: true
  _STATE_:
    <<: *test_db
    database: __STATE__test
    legacy: true
  gs_schooldb_rw:
    <<: *test_db
    database: gs_schooldb_test
    legacy: true
  gs_schooldb:
    <<: *test_db
    database: gs_schooldb_test
    legacy: true
  community_rw:
    <<: *test_db
    database: community_test
    legacy: true
  community:
    <<: *test_db
    database: community_test
    legacy: true
  us_geo_rw:
    <<: *test_db
    database: us_geo_test
    legacy: true
  us_geo:
    <<: *test_db
    database: us_geo_test
    legacy: true
  api_rw:
    <<: *test_db
    database: api_test
    legacy: true
  api:
    <<: *test_db
    database: api_test
    legacy: true
  gsdata:
    <<: *test_db
    database: gsdata_test
    legacy: false
  gsdata_rw:
    <<: *test_db
    database: gsdata_test
    legacy: false
  omni:
    <<: *test_db
    database: omni_test
    legacy: false
  omni_rw:
    <<: *test_db
    database: omni_test
    legacy: false

cucumber:
  <<: *test

profile:
  <<: *development

production:
  <<: *development

asset_precompilation:
  <<: *test
