mysql_production: &mysql_production
  <<: *mysql
  host: omega
  username: service
  password: service
mysql_production_rw: &mysql_production_rw
  <<: *mysql_production
mysql_production_ro: &mysql_production_ro
  <<: *mysql_production

production:
  <<: *mysql_production_ro
  database: localizedprofiles
  profile_config:
    <<: *mysql_production
    database: localizedprofiles
    legacy: false
  profile_config_ro:
    <<: *mysql_production_ro
    database: localizedprofiles

  al:
    <<: *mysql_production
    database: _al
    legacy: true
  al_ro:
    <<: *mysql_production_ro
    database: _al

  ak:
    <<: *mysql_production
    database: _ak
    legacy: true
  ak_ro:
    <<: *mysql_production_ro
    database: _ak

  az:
    <<: *mysql_production
    database: _az
    legacy: true
  az_ro:
    <<: *mysql_production_ro
    database: _az

  ar:
    <<: *mysql_production
    database: _ar
    legacy: true
  ar_ro:
    <<: *mysql_production_ro
    database: _ar

  ca:
    <<: *mysql_production
    database: _ca
    legacy: true
  ca_ro:
    <<: *mysql_production_ro
    database: _ca

  co:
    <<: *mysql_production
    database: _co
    legacy: true
  co_ro:
    <<: *mysql_production_ro
    database: _co

  ct:
    <<: *mysql_production
    database: _ct
    legacy: true
  ct_ro:
    <<: *mysql_production_ro
    database: _ct

  de:
    <<: *mysql_production
    database: _de
    legacy: true
  de_ro:
    <<: *mysql_production_ro
    database: _de

  dc:
    <<: *mysql_production
    database: _dc
    legacy: true
  dc_ro:
    <<: *mysql_production_ro
    database: _dc

  dc:
    <<: *mysql_production
    database: _dc
    legacy: true
  dc_ro:
    <<: *mysql_production_ro
    database: _dc

  fl:
    <<: *mysql_production
    database: _fl
    legacy: true
  fl_ro:
    <<: *mysql_production_ro
    database: _fl

  ga:
    <<: *mysql_production
    database: _ga
    legacy: true
  ga_ro:
    <<: *mysql_production_ro
    database: _ga

  hi:
    <<: *mysql_production
    database: _hi
    legacy: true
  hi_ro:
    <<: *mysql_production_ro
    database: _hi

  id:
    <<: *mysql_production
    database: _id
    legacy: true
  id_ro:
    <<: *mysql_production_ro
    database: _id

  il:
    <<: *mysql_production
    database: _il
    legacy: true
  il_ro:
    <<: *mysql_production_ro
    database: _il

  in:
    <<: *mysql_production
    database: _in
    legacy: true
  in_ro:
    <<: *mysql_production_ro
    database: _in

  ia:
    <<: *mysql_production
    database: _ia
    legacy: true
  ia_ro:
    <<: *mysql_production_ro
    database: _ia

  ks:
    <<: *mysql_production
    database: _ks
    legacy: true
  ks_ro:
    <<: *mysql_production_ro
    database: _ks

  ky:
    <<: *mysql_production
    database: _ky
    legacy: true
  ky_ro:
    <<: *mysql_production_ro
    database: _ky

  la:
    <<: *mysql_production
    database: _la
    legacy: true
  la_ro:
    <<: *mysql_production_ro
    database: _la

  me:
    <<: *mysql_production
    database: _me
    legacy: true
  me_ro:
    <<: *mysql_production_ro
    database: _me

  md:
    <<: *mysql_production
    database: _md
    legacy: true
  md_ro:
    <<: *mysql_production_ro
    database: _md

  ma:
    <<: *mysql_production
    database: _ma
    legacy: true
  ma_ro:
    <<: *mysql_production_ro
    database: _ma

  mi:
    <<: *mysql_production
    database: _mi
    legacy: true
  mi_ro:
    <<: *mysql_production_ro
    database: _mi

  mn:
    <<: *mysql_production
    database: _mn
    legacy: true
  mn_ro:
    <<: *mysql_production_ro
    database: _mn

  ms:
    <<: *mysql_production
    database: _ms
    legacy: true
  ms_ro:
    <<: *mysql_production_ro
    database: _ms

  mo:
    <<: *mysql_production
    database: _mo
    legacy: true
  mo_ro:
    <<: *mysql_production_ro
    database: _mo

  mt:
    <<: *mysql_production
    database: _mt
    legacy: true
  mt_ro:
    <<: *mysql_production_ro
    database: _mt

  ne:
    <<: *mysql_production
    database: _ne
    legacy: true
  ne_ro:
    <<: *mysql_production_ro
    database: _ne

  nv:
    <<: *mysql_production
    database: _nv
    legacy: true
  nv_ro:
    <<: *mysql_production_ro
    database: _nv

  nh:
    <<: *mysql_production
    database: _nh
    legacy: true
  nh_ro:
    <<: *mysql_production_ro
    database: _nh

  nj:
    <<: *mysql_production
    database: _nj
    legacy: true
  nj_ro:
    <<: *mysql_production_ro
    database: _nj

  nm:
    <<: *mysql_production
    database: _nm
    legacy: true
  nm_ro:
    <<: *mysql_production_ro
    database: _nm

  ny:
    <<: *mysql_production
    database: _ny
    legacy: true
  ny_ro:
    <<: *mysql_production_ro
    database: _ny

  nc:
    <<: *mysql_production
    database: _nc
    legacy: true
  nc_ro:
    <<: *mysql_production_ro
    database: _nc

  nd:
    <<: *mysql_production
    database: _nd
    legacy: true
  nd_ro:
    <<: *mysql_production_ro
    database: _nd

  oh:
    <<: *mysql_production
    database: _oh
    legacy: true
  oh_ro:
    <<: *mysql_production_ro
    database: _oh

  ok:
    <<: *mysql_production
    database: _ok
    legacy: true
  ok_ro:
    <<: *mysql_production_ro
    database: _ok

  or:
    <<: *mysql_production
    database: _or
    legacy: true
  or_ro:
    <<: *mysql_production_ro
    database: _or

  pa:
    <<: *mysql_production
    database: _pa
    legacy: true
  pa_ro:
    <<: *mysql_production_ro
    database: _pa

  ri:
    <<: *mysql_production
    database: _ri
    legacy: true
  ri_ro:
    <<: *mysql_production_ro
    database: _ri

  sc:
    <<: *mysql_production
    database: _sc
    legacy: true
  sc_ro:
    <<: *mysql_production_ro
    database: _sc

  sd:
    <<: *mysql_production
    database: _sd
    legacy: true
  sd_ro:
    <<: *mysql_production_ro
    database: _sd

  tn:
    <<: *mysql_production
    database: _tn
    legacy: true
  tn_ro:
    <<: *mysql_production_ro
    database: _tn

  tx:
    <<: *mysql_production
    database: _tx
    legacy: true
  tx_ro:
    <<: *mysql_production_ro
    database: _tx

  ut:
    <<: *mysql_production
    database: _ut
    legacy: true
  ut_ro:
    <<: *mysql_production_ro
    database: _ut

  vt:
    <<: *mysql_production
    database: _vt
    legacy: true
  vt_ro:
    <<: *mysql_production_ro
    database: _vt

  va:
    <<: *mysql_production
    database: _va
    legacy: true
  va_ro:
    <<: *mysql_production_ro
    database: _va

  wa:
    <<: *mysql_production
    database: _wa
    legacy: true
  wa_ro:
    <<: *mysql_production_ro
    database: _wa

  wv:
    <<: *mysql_production
    database: _wv
    legacy: true
  wv_ro:
    <<: *mysql_production_ro
    database: _wv

  wi:
    <<: *mysql_production
    database: _wi
    legacy: true
  wi_ro:
    <<: *mysql_production_ro
    database: _wi

  wy:
    <<: *mysql_production
    database: _wy
    legacy: true
  wy_ro:
    <<: *mysql_production_ro
    database: _wy

  gs_schooldb:
    <<: *mysql_production
    database: gs_schooldb
    legacy: true
  gs_schooldb_ro:
    <<: *mysql_production_ro
    database: gs_schooldb

  surveys:
    <<: *mysql_production
    database: surveys
    legacy: true
  surveys_ro:
    <<: *mysql_production_ro
    database: surveys
