<%%
# This file uses double percent signs in open erb tags, because this file will be stored in puppet by sys admins
# If you need to make changes so that additional db configurations can be used in production, just make the
# necessary changes, commit, and then send the file to a sys admin.

def define_db(name, db, legacy, includes)
  <<-EOF
  #{name}:
    <<: *#{includes}_rw
    database: #{db}
    legacy: #{legacy}
  #{name}_ro:
    <<: *#{includes}_ro
    database: #{db}
    legacy: #{legacy}
  EOF
end
%>

mysql_production: &mysql_production
  <<: *mysql
  host: omega
  username: service
  password: service
mysql_production_rw: &mysql_production_rw
  <<: *mysql_production
mysql_production_ro: &mysql_production_ro
  <<: *mysql_production


production: &production
  <<: *mysql_production
  database: LocalizedProfiles
<%%= define_db('profile_config', 'LocalizedProfiles', false, 'mysql_production') %>
<%% States.state_hash.values.each do |abbreviation| %>
<%%= define_db(abbreviation.downcase, '_' + abbreviation.downcase, true, 'mysql_production') %>
<%% end %>
<%%= define_db('gs_schooldb', 'gs_schooldb', true, 'mysql_production') %>
<%%= define_db('surveys', 'surveys', true, 'mysql_production') %>
<%%= define_db('community', 'community', true, 'mysql_production') %>

migrations-production: &migrations-production
  <<: *production
  username: service
  password: service


