mysql_production: &mysql_production
  <<: *mysql
  host: omega
  username: service
  password: service
mysql_production_rw: &mysql_production_rw
  <<: *mysql_production
mysql_production_ro: &mysql_production_ro
  <<: *mysql_production

production:
  <<: *mysql_production_ro
  database: LocalizedProfiles_production
<%= define_db('profile_config', 'LocalizedProfiles_production', false, 'mysql_production') %>
<% States.state_hash.values.each do |abbreviation| %>
<%= define_db(abbreviation.downcase, '_' + abbreviation.downcase, true, 'mysql_production') %>
<% end %>
<%= define_db('gs_schooldb', 'gs_schooldb', true, 'mysql_production') %>
<%= define_db('surveys', 'surveys', true, 'mysql_production') %>
