<% require 'States' %>
mysql: &mysql
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root

mysql_localhost: &mysql_localhost
  <<: *mysql
  host: 127.0.0.1
  password:

octopus:
  verify_connection: true
  environments:
    - development
    - test
  development:
    state_dbs:
    <% States.state_hash.values.each do |abbreviation| %>
      <%= abbreviation.upcase %>:
        <<: *mysql_localhost
        database: _<%= abbreviation.downcase %>
    <% end %>
    localized_profiles:
      gs_schooldb:
        <<: *mysql_localhost
        database: gs_schooldb
  test:
    state_dbs:
    <% States.state_hash.values.each do |abbreviation| %>
      <%= abbreviation.upcase %>:
        <<: *mysql_localhost
        database: _<%= abbreviation.downcase %>
    <% end %>
    localized_profiles:
      gs_schooldb:
        <<: *mysql_localhost
        database: gs_schooldb
