require 'features/page_objects/school_profiles_page'
require 'features/page_objects/account_page'

describe 'School profiles' do
  subject { SchoolProfilesPage.new }

  before do
    subject.load(state: 'california', city: 'alameda', school_id_and_name: '1-Alameda-High-School')
  end

  describe 'Submitting a new review' do
    
    context 'as an unregistered user', remote: true, type: :feature, js: true do
      it 'should indicate that my review is saved and ask me to verify my email' do
        pending 'Cannot reliably click the five-star rating'
        # choose five-star rating and fill out form
        subject.review_form.five_star_rating.click
        # save_and_open_screenshot
        subject.review_form.wait_until_rate_your_experience_textarea_visible(wait: 10)
        subject.review_form.rate_your_experience_textarea.set('This is a comment generated by rspec ' + Time.now.to_s)
        subject.review_form.submit_form

        subject.wait_until_join_modal_visible
        register_in_modal

        # Hover asking your relationship to school should appear. Choose Parent
        subject.wait_until_relationship_to_school_modal_visible
        subject.relationship_to_school_modal.parent.click
        subject.relationship_to_school_modal.submit_button.click
        subject.wait_until_relationship_to_school_modal_invisible(wait: 10)
        # save_and_open_screenshot
        expect(subject).to have_text('Thank you! One more step - please click on the verification link')
      end
    end

    context 'as a registered, but not signed in user' do
      it 'should prompt for sign-in'
      it 'should prompt for relationship to school'
      it 'should display review'
      it 'should send verify your review email'
    end

    context 'as a signed-in user' do
      it 'should prompt for relationship to school'
      it 'should display review right away'
      it 'should indicate that review has been submitted'
    end

    context 'submitting a second review for the same school' do
      it 'should open the form pre-filled with previous review'
    end

    it 'can be canceled'
    it 'requires a review of at least 7 words for main comment'
    it 'requires a review of at least 7 words for topical comment'
  end

  describe 'Displaying reviews' do
    context 'School with no reviews' do
      it 'Should prompt for first review' do
        # "Be the first to review this school"
      end
    end

    describe 'review summary' do
      it 'contains total number of reviews'
      it 'contains histogram with numbers per star rating'
      # The total number of reviews accounted for in the overall reviews histogram 
      # plus the number of reviews counted in the topical review summary right below 
      # should add up to the total number of reviews

      it 'review count accounts for star reviews plus topical reviews'

      # does giving a star rating and a topical rating count as two reviews?

      it 'displays topical reviews with counts'

      it 'allows hovering on topical review for histogram'

      it 'displays comments with star ratings'

      it 'Show More allows displaying more than five comments'
    end
  end

  describe 'Reporting a review' do
    it 'should be cancelable'
    
    context 'as a signed-in user' do
      # Button turns fuschia/red and inner text changes to “Review Reported”
      it 'indicates that the review was reported'  
    end

    context 'as a new user' do
      # "Before you can report this review, you'll need to log in or create an account."
      it 'prompts to sign in or sign up'
      it 'indicated that the review was reported after authentication'
    end

    context 'topical reviews' do
      it 'indicates that the review was reported'  
    end
  end
end