require 'remote_spec_helper'
require 'features/page_objects/school_profiles_page'

describe 'school name shows up on a preschool profile', type: :feature, remote: true do
  before { visit '/new-jersey/newark/preschools/Broadway-Mini-Mall-Head-Start/7453/' }
  subject(:page_object) { SchoolProfilesPage.new }
  its(:h1) { is_expected.to have_text('Broadway Mini Mall Head Start') }
end

describe 'submit a review while signed out', type: :feature, remote: true do
  it 'submits the review after signing in with facebook' do
    pending 'Need to allow all facebook urls in the correct spec helper file. But still doesn\'t work. Enable webkit debug and see logs.'
    fail
    # within('.join-and-login') do
    #   click_button 'Sign up with facebook'
    # end
    # submit_facebook_adam
    # page.should have_content('All set! We have submitted your review. Thank you for helping other families by sharing your experiences.
  end
end

describe 'while signed in as facebook user', type: :feature, remote: true do
  it 'when I submit a review it is acknowledged' do
    sign_in_as_facebook_adam
    visit('/california/alameda/1-Alameda-High-School/')
    first('.five-star-question-cta__star').click
    within('.review-form') do
      all('textarea').last.set('this is a comment generated by rspec ' + Time.now.to_s)
      click_button('Submit')
    end
    expect(page).to have_text('All set! We have submitted your review')
  end
end
