# require 'json'
file = File.open('final_test_scores_gsdata.json',"r")
# hash = JSON.parse(file)
require "json"
def parse_json_with_symbolized_keys(filename)
  JSON.parse(File.read(filename), :symbolize_names => true)
end

states =  parse_json_with_symbolized_keys(file)
breakdowns = []
states.each do |hash|
  breakdowns << hash[:breakdowns]
end

p breakdowns.flatten.uniq.compact

# Ratings - ["African American", "White", "Male", "Female", "Students with disabilities", "General-Education students", "Not limited English proficient", "All Students", "Hispanic", "Native American", "Two or more races", "Native Hawaiian or Other Pacific Islander", "Asian or Pacific Islander", "Limited English proficient", "Asian", "Economically disadvantaged", "Not economically disadvantaged", "non-frl award winning school", "frl award winning school"]
# Characteristics - ["All students", "White", "Hispanic", "Black", "Two or more races", "Asian or Asian/Pacific Islander", "American Indian/Alaska Native", "Asian", "Native American or Native Alaskan", "Students with disabilities", "Poverty", "Multiracial", "African American", "Limited English proficient", "Native Hawaiian or Other Pacific Islander", "Hawaiian Native/Pacific Islander", "Female", "Male", "Economically disadvantaged", "Migrant", "Pacific Islander", "Asian or Pacific Islander", "Filipino", "General-Education students", "Not economically disadvantaged", "Not limited English proficient", "Native American", "Hawaiian", "Asian/Pacific Islander", "Black, not Hispanic", "White, not Hispanic", "American Indian/Alaskan Native", "Native Hawaiian or Pacific Islander", "Unspecified", "Not migrant", "African-American", "Native Hawaiian", "American Indian"]
# GSData - ["Hispanic", "African American", "White", "Two or more races", "Limited English proficient", "Students with IDEA catagory disabilities", "Male", "Female","All Students", "Students with disabilities", "All students except 504 category,Hispanic,Male", "All students except 504 category,Female,Hispanic", "All students except 504 category,Hispanic", "African American,All students except 504 category", "All students except 504 category,Male,White", "All students except 504 category,Female,White", "All students except 504 category,White", "All students except 504 category,Two or more races", "All students except 504 category,Limited English proficient,Male", "All students except 504 category,Female,Limited English proficient", "All students except 504 category,Limited English proficient", "All students except 504 category,Male", "All students except 504 category,Female", "All students except 504 category", "Students with 504 catagory disabilities", "African American,All students except 504 category,Male", "African American,All students except 504 category,Female", "Native American", "Asian", "Native Hawaiian or Other Pacific Islander", "All students except 504 category,Male,Two or more races", "All students except 504 category,Female,Two or more races", "All students except 504 category,Asian,Male", "All students except 504 category,Asian,Female", "All students except 504 category,Asian", "All students except 504 category,Native American", "All students except 504 category,Female,Native American", "All students except 504 category,Male,Native American", "All students except 504 category,Native Hawaiian or Other Pacific Islander", "All students except 504 category,Female,Native Hawaiian or Other Pacific Islander", "All students except 504 category,Male,Native Hawaiian or Other Pacific Islander"]
# Test Scores GSData - ["White", "Hispanic", "General population", "Not limited English proficient", "Limited English proficient", "Not poverty", "Poverty", "Students with disabilities", "Male", "Reduced lunch eligible", "Free lunch eligible", "Female", "All students", "Not economically disadvantaged", "General-Education students", "Migrant", "Not migrant", "Economically disadvantaged", "Two or more races", "African American", "Asian or Pacific Islander", "Native American", "Special Education with Accomodation", "Asian", "Homeless", "Native Hawaiian or Other Pacific Islander", "Fluent-English Proficient and English Only", "Reclassified-Fluent English Proficient", "Parents Not High School Graduate", "Parents High School Graduate", "Initially-Fluent English Proficient", "Parents Comm/Jr College Graduate", "Parents Four Year College Graduate", "Parents Education - Declined to State", "Filipino", "ParentsGraduate Degree", "English Learners Enrolled in School in the U.S. 12 Months or More", "English Learners Enrolled in School in the U.S. Less Than 12 Months", "Neither migrant nor immigrant", "Immigrant", "Other ethnicity","Pacific Islander", "Title I", "Limited English Proficient Current Plus Former", "English Language Learner Exited", "Former LEP student - monitoring year 2", "Former LEP student - monitoring year 1", "", "Limited English Proficient Former", "English Language Learner Current", "Gifted", "Hawaiian", "Not Gifted", "Not Homeless"]