Insert into community.alert_words (word, really_bad) values('Gulen',1)
Insert into community.alert_words (word, really_bad) values('f*ck',1)
Insert into community.alert_words (word, really_bad) values('https',1)
Insert into community.alert_words (word, really_bad) values('narcissist',1)
Insert into community.alert_words (word, really_bad) values('shittiest',1)
Insert into community.alert_words (word, really_bad) values('trashy',0)
Insert into community.alert_words (word, really_bad) values('weed',0)
Insert into community.alert_words (word, really_bad) values('Trump',0)
Insert into community.alert_words (word, really_bad) values('MAGA',0)
Insert into community.alert_words (word, really_bad) values('Mexican',0)
Insert into community.alert_words (word, really_bad) values('Mexicans',0)
Insert into community.alert_words (word, really_bad) values('Asians',0)
Insert into community.alert_words (word, really_bad) values('Jew',0)
Insert into community.alert_words (word, really_bad) values('Jews',0)
Insert into community.alert_words (word, really_bad) values('Indian',0)
Insert into community.alert_words (word, really_bad) values('Indians',0)
Insert into community.alert_words (word, really_bad) values('Chinks',1)
Insert into community.alert_words (word, really_bad) values('Coons',1)
Insert into community.alert_words (word, really_bad) values('Colored',1)
Insert into community.alert_words (word, really_bad) values('Coloreds',1)
Insert into community.alert_words (word, really_bad) values('Gooks',1)
Insert into community.alert_words (word, really_bad) values('Japs',1)
Insert into community.alert_words (word, really_bad) values('Oriental',1)
Insert into community.alert_words (word, really_bad) values('Orientals',1)
Insert into community.alert_words (word, really_bad) values('Dinks',1)
Insert into community.alert_words (word, really_bad) values('Sand niggers',1)
Insert into community.alert_words (word, really_bad) values('Towel heads',1)
Insert into community.alert_words (word, really_bad) values('Rag head',1)
Insert into community.alert_words (word, really_bad) values('Rag heads',1)
Insert into community.alert_words (word, really_bad) values('Towelheads',1)
Insert into community.alert_words (word, really_bad) values('Raghead',1)
Insert into community.alert_words (word, really_bad) values('Ragheads',1)
Insert into community.alert_words (word, really_bad) values('Beaners',1)
Insert into community.alert_words (word, really_bad) values('Wetbacks',1)
Insert into community.alert_words (word, really_bad) values('Wet back',1)
Insert into community.alert_words (word, really_bad) values('Cracker',1)
Insert into community.alert_words (word, really_bad) values('Crackers',1)
Insert into community.alert_words (word, really_bad) values('Kikes',1)
Insert into community.alert_words (word, really_bad) values('Kykes',1)
Insert into community.alert_words (word, really_bad) values('shady',0)
Insert into community.alert_words (word, really_bad) values('manipulative',1)
Insert into community.alert_words (word, really_bad) values('phony',0)
Insert into community.alert_words (word, really_bad) values('illegal',1)
Insert into community.alert_words (word, really_bad) values('dragging',0)
Insert into community.alert_words (word, really_bad) values('drag',0)
